# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 200

checkpoint:
  save_interval: 1000
  save_interval_updates: 50
  keep_interval_updates: 1
  no_epoch_checkpoints: true
  best_checkpoint_metric: wer

task:
  _name: audio_finetuning
  data: ???
  normalize: false
  labels: ltr

dataset:
  num_workers: 6
  max_tokens: 3200000
  skip_invalid_size_inputs_valid_test: true
  validate_after_updates: 10000
  validate_interval: 1000
  valid_subset: dev_other

distributed_training:
  ddp_backend: no_c10d
  distributed_backend: 'nccl'
  distributed_world_size: 1
  nprocs_per_node: 4
  find_unused_parameters: true

criterion:
  _name: ctc
  zero_infinity: true

optimization:
  max_update: 13000
  lr: [0.00005]
  sentence_avg: true
  update_freq: [4]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: tri_stage
  phase_ratio: [0.1, 0.4, 0.5]
  final_lr_scale: 0.05

model:
  _name: wav2vec_ctc
  w2v_path: ???
  apply_mask: true
  mask_prob: 0.65
  mask_channel_prob: 0.25
  mask_channel_length: 64
  layerdrop: 0.1
  activation_dropout: 0.1
  feature_grad_mult: 0.0
  freeze_finetune_updates: 10000

hydra:
  job:
    config:
      override_dirname:
        kv_sep: '-'
        item_sep: '__'
        exclude_keys:
          - run
          - distributed_training.distributed_port
          - task.data
  sweep:
    dir: /gpfsstore/rech/iqh/upp27cx/w2v2_10h_test
    subdir: max_update__${optimization.max_update}-lr__${optimization.lr}-adapter__${model.adapter_name}-freeze_updates__${model.freeze_finetune_updates}-lang__${lang}-adapter_layers__${model.adapter_layers}
  launcher:
    cpus_per_task: 40
    gpus_per_node: 1
    tasks_per_node: 1
    nodes: 1
    partition: gpu_p13
    additional_parameters:
      account: iqh@gpu
      qos: qos_gpu-dev
    mem_gb: 50
    timeout_min: 120
    constraint: v100-32g
    submitit_folder: ${hydra.sweep.dir}/submitit/%j
